include: package:hexy_dart_lint/analysis_options.yaml

analyzer:
  exclude:
    - lib/generated/*
    - lib/generated/intl/*
    - lib/l10n/*
    - lib/**/*.g.dart

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_in_for_each: true
    no_logic_in_create_state: true
    use_key_in_widget_constructors: true
    avoid_catches_without_on_clauses: true
    avoid_catching_errors: true
    avoid_field_initializers_in_const_classes: true
    avoid_function_literals_in_foreach_calls: true
    avoid_positional_boolean_parameters: true
    avoid_renaming_method_parameters: true
    avoid_types_on_closure_parameters: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    cascade_invocations: true
    cast_nullable_to_non_nullable: true
    constant_identifier_names: true
    deprecated_consistency: true
    exhaustive_cases: true
    file_names: true
    implementation_imports: true
    join_return_with_assignment: true
    missing_whitespace_between_adjacent_strings: true
    one_member_abstracts: true
    overridden_fields: true
    parameter_assignments: true
    prefer_asserts_in_initializer_lists: true
    prefer_asserts_with_message: true
    prefer_final_locals: true
    prefer_function_declarations_over_variables: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_is_not_operator: true
    prefer_mixin: true
    prefer_null_aware_operators: true
    unnecessary_await_in_return: true
    sized_box_for_whitespace: true
    tighten_type_of_initializing_formals: true
    type_annotate_public_apis: true
    unnecessary_lambdas: true
    unnecessary_null_aware_assignments: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_setters_to_change_properties: true
    use_string_buffers: true
    use_to_and_as_if_applicable: true
    void_checks: true
    omit_local_variable_types: false
    #   style:
    always_put_required_named_parameters_first: true
    lines_longer_than_80_chars: false
    avoid_escaping_inner_quotes: true
    flutter_style_todos: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    prefer_int_literals: true
    prefer_interpolation_to_compose_strings: true
#    public_member_api_docs
