name: game_stat
description: A new game stat application.
author: mozerrr
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.0.0
  intl: ^0.17.0
  equatable: ^2.0.0
#  dio: ^4.0.0
  shared_preferences: ^2.0.5
#  native_admob_flutter: ^1.3.0
#  json_serializable: ^4.1.1
#  path_provider: ^2.0.1
#  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.1
  hexy_dart_lint:
    git:
      url: git@github.com:fildenisov/hexy-dart-lint.git
      ref: 1.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/fonts/

  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/helveticaneuecyr-thin.ttf
          weight: 100
        - asset: assets/fonts/helveticaneuecyr-light.ttf
          weight: 300
        - asset: assets/fonts/helveticaneuecyr-roman.ttf
          weight: 400
        - asset: assets/fonts/helveticaneuecyr-medium.ttf
          weight: 500
        - asset: assets/fonts/helveticaneuecyr-bold.ttf
          weight: 700
        - asset: assets/fonts/helveticaneuecyr-heavy.ttf
          weight: 800
        - asset: assets/fonts/helveticaneuecyr-black.ttf
          weight: 900
#flutter_intl:
#  enabled: true
